# -*- coding: utf-8 -*-
"""metode1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-5Pabfzevp_irAlPw9en0a-nsQLLlYzE
"""

print("This is droga Amsterdam")
x=5
y=16
print(float(x))
print(y/x)

"""y=sin(x1)+cos(x2), x pripada 0.2*pi"""

x1=np.arange(0.2*pi,0.1)
x2=np.arange(0.2*pi,0.1)

x1m,x2m=np.meshgrid(x1,x2)

y=np.sin(x1m)+np.cos(x2m)

fig=plt.figure()
ax=fig.add_subplot(111,projection='3d')

#plt.plot(y)
#plt.show()

import numpy as np
import matplotlib.pyplot as plt

x=np.array([0,0.5,1,1.5,2,2.5,3,3.5,4,4.5])
x1=np.arange(0,5,0.5)
x2=np.linspace(0,4.5,10)
y=np.array([1,2,3,2,2,2,1.5,2,2,2.5])
print (x2)

plt.plot(x,y)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from numpy import pi
#komentar
"""vise
linija"""
x=np.arange(0,2*pi,0.1)
y=np.sin(x)
#ako uvedemo math biblioteku math.sin(x)
plt.plot(x,y)
plt.show()

"""y=sin(X), x pripada intervalu [0.2*pi]"""